before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev

language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

notifications:
  slack:
    secure: PTbvl2gYiwheamcZUDsccTANv7dgraDzgV3JMUhQ0V8Omds5+P3AqnmEL2T+DNoDbTJeYDeCNlUQCHFjKuEAk2lvCXzmX9opDB9WylbwMtJ34bQVYk8dDBKTjOgirUmdWv2ghAws2ZpPTgO2zVocr61oh/VCctMEPU+p6aBwnXT3sShbUPJ68qJjR6ZI720IvfqjR2VW6Zdw5ynaKMetrTakUPej/uNdig5g/7iZww7bbpehr47aYS322YwYcQ9vezfC9SSiynqHw9yJR7L7iArfySVXQjOZ4WAGm1qhYJs7s0ELwi8eTgso79cl9CuIdsSnvzPXDs83pi1jP8y/CCcdq8wU6fbZwoHUK95yBJzgnEvfC577Fr0F4vCn617FoHfsHylM8ThUzPBors01KTDeCf6bgLpP6aQ2+NSGX6+DOP9tn5I0Fr8l6E5Eev7wmH9xXYc8agaKoImrvuhGZp38YbZIllO9erCfiIh4oV7peJY3jJt0u0uEzzXZCaJdOlxFh4x4xhMUZ184sr16l6sgTB1PjyUpXVD01OoGxtPwmlKtYLvBnV1JJu5AgLaeV2NWBHJL+7lxiEa32GhAxG2kAv/zhY++C7D4dvQCPZN5DMEXWhbXLeTa8vU7Rf6XTqhfPlAeQG19rSRFPWl8k4yois29Ot5SV9i23AYJygc=
