#! /bin/bash

# set -x

### BEGIN INIT INFO
# Provides:             pythonbot
# Required-Start:       $network $syslog $named
# Required-Stop:        $network $syslog $named
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Pythonbot
# Description:          Pythonbot
### END INIT INFO

ME=$(readlink -f $0)
SCRIPT=$(basename $ME)
export LOGFILE=/var/log/$(basename $SCRIPT .sh).log
export PIDFILE=/var/run/$(basename $SCRIPT .sh).pid

function start {
  . /home/pi/slack_pythonbot
  /home/pi/slackbot.py
  return $?
}

function stop {
  PID=$(cat $PIDFILE)
  rm -f ${PIDFILE}
  kill -9 $PID
  return $?
}

function restart {
  stop
  start
}

case "$1" in
  start)
    start
    RET=$?
    ;;
  stop)
    stop
    RET=$?
    ;;
  restart)
    restart
    RET=$?
    ;;
  *)
    echo "Usage: $0 {start/stop/restart}"
    ;;
esac

exit ${RET}

